# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8ac20e202fb84ad34e8aaba4012f85f55be0a77fcd53a77c374de0d49ff64599f2348b764c7448bad562aa5a63123c4224b4d4c3db97c5eb91ffa9196a577cad
  twilio_number: <%= ENV["TWILIO_NUMBER"] %>
  auth_sid: <%= ENV["TWILIO_AUTH_SID"] %>
  auth_token: <%= ENV["TWILIO_AUTH_TOKEN"] %>

test:
  secret_key_base: 479c5466cb763e360a14c7ce3c0ffccf28fb63bf7b2eb8f9aca27c1292f7c22d3fc6e2e2176bdf8afa4502960109955c2e9388c81b1d3b19436d0be1b8a55d37

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  twilio_number: <%= ENV["TWILIO_NUMBER"] %>
  auth_sid: <%= ENV["TWILIO_AUTH_SID"] %>
  auth_token: <%= ENV["TWILIO_AUTH_TOKEN"] %>

